name: APP (Build)

on:
  workflow_dispatch:
  push:
    branches:
      - emerald-trigger

jobs:
  pre-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          insecure: true
          body: '{"event": "deployment"}'